App\Domain\Product\ExampleProduct:
  type: entity
  repositoryClass: App\Infrastructure\Persistence\Doctrine\Repository\ExampleProductRepository
  table: product
  id:
    id:
      type: smallint
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: false
      options:
        comment: 'name'
    price:
      type: integer
      options:
        comment: 'price'
